
package co.com.santander.accesorecursos.soap.resources.documentos;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T22:29:03.021+02:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "WSBusinessRuleException", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/")
public class WSBusinessRuleException extends Exception {
    
    private co.com.santander.accesorecursos.soap.resources.documentos.FaultBean wsBusinessRuleException;

    public WSBusinessRuleException() {
        super();
    }
    
    public WSBusinessRuleException(String message) {
        super(message);
    }
    
    public WSBusinessRuleException(String message, Throwable cause) {
        super(message, cause);
    }

    public WSBusinessRuleException(String message, co.com.santander.accesorecursos.soap.resources.documentos.FaultBean wsBusinessRuleException) {
        super(message);
        this.wsBusinessRuleException = wsBusinessRuleException;
    }

    public WSBusinessRuleException(String message, co.com.santander.accesorecursos.soap.resources.documentos.FaultBean wsBusinessRuleException, Throwable cause) {
        super(message, cause);
        this.wsBusinessRuleException = wsBusinessRuleException;
    }

    public co.com.santander.accesorecursos.soap.resources.documentos.FaultBean getFaultInfo() {
        return this.wsBusinessRuleException;
    }
}
