
package co.com.santander.accesorecursos.soap.resources.documentos;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T22:29:03.210+02:00
 * Generated source version: 2.7.2
 * 
 */
 
public class WsFelec_WsFelecPort_Server{

    protected WsFelec_WsFelecPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new WsFelecImpl();
        String address = "https://felec.computec.com/WSFelecJAXWSP/WsFelecService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new WsFelec_WsFelecPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
