
package co.com.santander.accesorecursos.soap.resources.documentos;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T22:29:02.948+02:00
 * Generated source version: 2.7.2
 * 
 */
public final class WsFelec_WsFelecPort_Client {

    private static final Logger LOG = Logger.getLogger(WsFelec_WsFelecPort_Client.class.getName());

    private static final QName SERVICE_NAME = new QName("http://co.com.computec.wsservicioselectronicos.ws/", "WsFelecService");

    private WsFelec_WsFelecPort_Client() {
    }



}
