package co.com.santander.accesorecursos.soap.resources.documentos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T22:29:03.174+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", name = "WsFelec")
@XmlSeeAlso({ObjectFactory.class})
public interface WsFelec {

    @WebMethod
    @Action(input = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumentoRequest", output = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumentoResponse", fault = {@FaultAction(className = WSBusinessRuleException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumento/Fault/WSBusinessRuleException"), @FaultAction(className = WSSystemException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumento/Fault/WSSystemException")})
    @RequestWrapper(localName = "obtenerDocumento", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.ObtenerDocumento")
    @ResponseWrapper(localName = "obtenerDocumentoResponse", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.ObtenerDocumentoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] obtenerDocumento(
            @WebParam(name = "consultaDocDTO", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO consultaDocDTO,
            @WebParam(name = "beanDatosCliente", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente beanDatosCliente
    ) throws WSBusinessRuleException, WSSystemException;

    @WebMethod
    @Action(input = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumentoIdRequest", output = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumentoIdResponse", fault = {@FaultAction(className = WSBusinessRuleException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumentoId/Fault/WSBusinessRuleException"), @FaultAction(className = WSSystemException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumentoId/Fault/WSSystemException")})
    @RequestWrapper(localName = "enviarMailDocumentoId", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.EnviarMailDocumentoId")
    @ResponseWrapper(localName = "enviarMailDocumentoIdResponse", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.EnviarMailDocumentoIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String enviarMailDocumentoId(
            @WebParam(name = "consultaDocDTO", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO consultaDocDTO,
            @WebParam(name = "beanDatosCliente", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente beanDatosCliente,
            @WebParam(name = "datoEnvioDTO", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.DatoEnvioDTO datoEnvioDTO
    ) throws WSBusinessRuleException, WSSystemException;

    @WebMethod
    @Action(input = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/consultarDocumentosRequest", output = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/consultarDocumentosResponse", fault = {@FaultAction(className = WSBusinessRuleException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/consultarDocumentos/Fault/WSBusinessRuleException"), @FaultAction(className = WSSystemException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/consultarDocumentos/Fault/WSSystemException")})
    @RequestWrapper(localName = "consultarDocumentos", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.ConsultarDocumentos")
    @ResponseWrapper(localName = "consultarDocumentosResponse", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.ConsultarDocumentosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ResultadoConsultaDTO> consultarDocumentos(
            @WebParam(name = "consultaDocDTO", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO consultaDocDTO,
            @WebParam(name = "beanDatosCliente", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente beanDatosCliente
    ) throws WSBusinessRuleException, WSSystemException;

    @WebMethod
    @Action(input = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumentoIdRequest", output = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumentoIdResponse", fault = {@FaultAction(className = WSBusinessRuleException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumentoId/Fault/WSBusinessRuleException"), @FaultAction(className = WSSystemException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/obtenerDocumentoId/Fault/WSSystemException")})
    @RequestWrapper(localName = "obtenerDocumentoId", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.ObtenerDocumentoId")
    @ResponseWrapper(localName = "obtenerDocumentoIdResponse", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.ObtenerDocumentoIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] obtenerDocumentoId(
            @WebParam(name = "consultaDocDTO", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO consultaDocDTO,
            @WebParam(name = "beanDatosCliente", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente beanDatosCliente
    ) throws WSBusinessRuleException, WSSystemException;

    @WebMethod
    @Action(input = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumentoRequest", output = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumentoResponse", fault = {@FaultAction(className = WSBusinessRuleException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumento/Fault/WSBusinessRuleException"), @FaultAction(className = WSSystemException.class, value = "http://co.com.computec.wsservicioselectronicos.ws/WsFelec/enviarMailDocumento/Fault/WSSystemException")})
    @RequestWrapper(localName = "enviarMailDocumento", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.EnviarMailDocumento")
    @ResponseWrapper(localName = "enviarMailDocumentoResponse", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/", className = "co.com.santander.accesorecursos.soap.resources.documentos.EnviarMailDocumentoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String enviarMailDocumento(
            @WebParam(name = "consultaDocDTO", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO consultaDocDTO,
            @WebParam(name = "beanDatosCliente", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente beanDatosCliente,
            @WebParam(name = "datoEnvioDTO", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.documentos.DatoEnvioDTO datoEnvioDTO
    ) throws WSBusinessRuleException, WSSystemException;
}
