
package co.com.santander.accesorecursos.soap.resources.documentos;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T22:29:02.948+02:00
 * Generated source version: 2.7.2
 * 
 */
public final class WsFelec_WsFelecPort_Client {

    private static final Logger LOG = Logger.getLogger(WsFelec_WsFelecPort_Client.class.getName());

    private static final QName SERVICE_NAME = new QName("http://co.com.computec.wsservicioselectronicos.ws/", "WsFelecService");

    private WsFelec_WsFelecPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WsFelecService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                LOG.severe(e.getMessage());
            }
        }
      
        WsFelecService ss = new WsFelecService(wsdlURL, SERVICE_NAME);
        WsFelec port = ss.getWsFelecPort();  
        
        {
        System.out.println("Invoking obtenerDocumento...");
        co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO _obtenerDocumento_consultaDocDTO = null;
        co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente _obtenerDocumento_beanDatosCliente = null;
        try {
            byte[] _obtenerDocumento__return = port.obtenerDocumento(_obtenerDocumento_consultaDocDTO, _obtenerDocumento_beanDatosCliente);
            System.out.println("obtenerDocumento.result=" + _obtenerDocumento__return);

        } catch (WSBusinessRuleException e) { 
            System.out.println("Expected exception: WSBusinessRuleException has occurred.");
            System.out.println(e.toString());
        } catch (WSSystemException e) { 
            System.out.println("Expected exception: WSSystemException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking enviarMailDocumentoId...");
        co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO _enviarMailDocumentoId_consultaDocDTO = null;
        co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente _enviarMailDocumentoId_beanDatosCliente = null;
        co.com.santander.accesorecursos.soap.resources.documentos.DatoEnvioDTO _enviarMailDocumentoId_datoEnvioDTO = null;
        try {
            String _enviarMailDocumentoId__return = port.enviarMailDocumentoId(_enviarMailDocumentoId_consultaDocDTO, _enviarMailDocumentoId_beanDatosCliente, _enviarMailDocumentoId_datoEnvioDTO);
            System.out.println("enviarMailDocumentoId.result=" + _enviarMailDocumentoId__return);

        } catch (WSBusinessRuleException e) { 
            System.out.println("Expected exception: WSBusinessRuleException has occurred.");
            System.out.println(e.toString());
        } catch (WSSystemException e) { 
            System.out.println("Expected exception: WSSystemException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarDocumentos...");
        co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO _consultarDocumentos_consultaDocDTO = null;
        co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente _consultarDocumentos_beanDatosCliente = null;
        try {
            java.util.List<ResultadoConsultaDTO> _consultarDocumentos__return = port.consultarDocumentos(_consultarDocumentos_consultaDocDTO, _consultarDocumentos_beanDatosCliente);
            System.out.println("consultarDocumentos.result=" + _consultarDocumentos__return);

        } catch (WSBusinessRuleException e) { 
            System.out.println("Expected exception: WSBusinessRuleException has occurred.");
            System.out.println(e.toString());
        } catch (WSSystemException e) { 
            System.out.println("Expected exception: WSSystemException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obtenerDocumentoId...");
        co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO _obtenerDocumentoId_consultaDocDTO = null;
        co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente _obtenerDocumentoId_beanDatosCliente = null;
        try {
            byte[] _obtenerDocumentoId__return = port.obtenerDocumentoId(_obtenerDocumentoId_consultaDocDTO, _obtenerDocumentoId_beanDatosCliente);
            System.out.println("obtenerDocumentoId.result=" + _obtenerDocumentoId__return);

        } catch (WSBusinessRuleException e) { 
            System.out.println("Expected exception: WSBusinessRuleException has occurred.");
            System.out.println(e.toString());
        } catch (WSSystemException e) { 
            System.out.println("Expected exception: WSSystemException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking enviarMailDocumento...");
        co.com.santander.accesorecursos.soap.resources.documentos.ConsultaDocDTO _enviarMailDocumento_consultaDocDTO = null;
        co.com.santander.accesorecursos.soap.resources.documentos.BeanDatosCliente _enviarMailDocumento_beanDatosCliente = null;
        co.com.santander.accesorecursos.soap.resources.documentos.DatoEnvioDTO _enviarMailDocumento_datoEnvioDTO = null;
        try {
            String _enviarMailDocumento__return = port.enviarMailDocumento(_enviarMailDocumento_consultaDocDTO, _enviarMailDocumento_beanDatosCliente, _enviarMailDocumento_datoEnvioDTO);
            System.out.println("enviarMailDocumento.result=" + _enviarMailDocumento__return);

        } catch (WSBusinessRuleException e) { 
            System.out.println("Expected exception: WSBusinessRuleException has occurred.");
            System.out.println(e.toString());
        } catch (WSSystemException e) { 
            System.out.println("Expected exception: WSSystemException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
