
package co.com.santander.accesorecursos.soap.resources.documentos;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T22:29:03.048+02:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "WSSystemException", targetNamespace = "http://co.com.computec.wsservicioselectronicos.ws/")
public class WSSystemException extends Exception {
    
    private co.com.santander.accesorecursos.soap.resources.documentos.FaultBean wsSystemException;

    public WSSystemException() {
        super();
    }
    
    public WSSystemException(String message) {
        super(message);
    }
    
    public WSSystemException(String message, Throwable cause) {
        super(message, cause);
    }

    public WSSystemException(String message, co.com.santander.accesorecursos.soap.resources.documentos.FaultBean wsSystemException) {
        super(message);
        this.wsSystemException = wsSystemException;
    }

    public WSSystemException(String message, co.com.santander.accesorecursos.soap.resources.documentos.FaultBean wsSystemException, Throwable cause) {
        super(message, cause);
        this.wsSystemException = wsSystemException;
    }

    public co.com.santander.accesorecursos.soap.resources.documentos.FaultBean getFaultInfo() {
        return this.wsSystemException;
    }
}
