
package co.com.santander.accesorecursos.soap.resources.token.co.experian.computec.sts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ComputecSTSService", targetNamespace = "http://sts.computec.experian.co/", wsdlLocation = "https://felec.computec.com/WSSAMLPruebas/ComputecSTSService/ComputecSTSService.wsdl")
public class ComputecSTSService
    extends Service
{

    private final static URL COMPUTECSTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPUTECSTSSERVICE_EXCEPTION;
    private final static QName COMPUTECSTSSERVICE_QNAME = new QName("http://sts.computec.experian.co/", "ComputecSTSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://felec.computec.com/WSSAMLPruebas/ComputecSTSService/ComputecSTSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPUTECSTSSERVICE_WSDL_LOCATION = url;
        COMPUTECSTSSERVICE_EXCEPTION = e;
    }

    public ComputecSTSService() {
        super(__getWsdlLocation(), COMPUTECSTSSERVICE_QNAME);
    }

    public ComputecSTSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPUTECSTSSERVICE_QNAME, features);
    }

    public ComputecSTSService(URL wsdlLocation) {
        super(wsdlLocation, COMPUTECSTSSERVICE_QNAME);
    }

    public ComputecSTSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPUTECSTSSERVICE_QNAME, features);
    }

    public ComputecSTSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComputecSTSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ComputecSTSDelegate
     */
    @WebEndpoint(name = "ComputecSTSPort")
    public ComputecSTSDelegate getComputecSTSPort() {
        return super.getPort(new QName("http://sts.computec.experian.co/", "ComputecSTSPort"), ComputecSTSDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComputecSTSDelegate
     */
    @WebEndpoint(name = "ComputecSTSPort")
    public ComputecSTSDelegate getComputecSTSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sts.computec.experian.co/", "ComputecSTSPort"), ComputecSTSDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPUTECSTSSERVICE_EXCEPTION!= null) {
            throw COMPUTECSTSSERVICE_EXCEPTION;
        }
        return COMPUTECSTSSERVICE_WSDL_LOCATION;
    }

}
