
package co.com.santander.accesorecursos.soap.resources.token.co.experian.computec.sts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComputecSTSDelegate", targetNamespace = "http://sts.computec.experian.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComputecSTSDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerToken", targetNamespace = "http://sts.computec.experian.co/", className = "co.experian.computec.sts.ObtenerToken")
    @ResponseWrapper(localName = "obtenerTokenResponse", targetNamespace = "http://sts.computec.experian.co/", className = "co.experian.computec.sts.ObtenerTokenResponse")
    @Action(input = "http://sts.computec.experian.co/ComputecSTSDelegate/obtenerTokenRequest", output = "http://sts.computec.experian.co/ComputecSTSDelegate/obtenerTokenResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://sts.computec.experian.co/ComputecSTSDelegate/obtenerToken/Fault/Exception")
    })
    public String obtenerToken(
        @WebParam(name = "arg0", targetNamespace = "")
        ComputecSTSDTO arg0)
        throws Exception_Exception
    ;

}
