
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package co.com.santander.accesorecursos.soap.resources.token;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T08:16:50.892+02:00
 * Generated source version: 2.7.2
 */

@WebService(
        serviceName = "ComputecSTSService",
        portName = "ComputecSTSPort",
        targetNamespace = "http://sts.computec.experian.co/",
        wsdlLocation = "https://felec.computec.com/WSSAMLPruebas/ComputecSTSService/ComputecSTSService.wsdl",
        endpointInterface = "co.com.santander.accesorecursos.soap.resources.token.ComputecSTSDelegate")

public class ComputecSTSDelegateImpl implements ComputecSTSDelegate {

    private static final Logger LOG = Logger.getLogger(ComputecSTSDelegateImpl.class.getName());

    /* (non-Javadoc)
     * @see co.com.santander.accesorecursos.soap.resources.token.ComputecSTSDelegate#obtenerToken(co.com.santander.accesorecursos.soap.resources.token.ComputecSTSDTO  arg0 )*
     */
    public String obtenerToken(co.com.santander.accesorecursos.soap.resources.token.ComputecSTSDTO arg0) throws Exception_Exception {
        LOG.info("Executing operation obtenerToken");
        System.out.println(arg0);
        try {
            String _return = "";
            return _return;
        } catch (Throwable ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
