package co.com.santander.accesorecursos.soap.resources.token;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T08:16:50.915+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://sts.computec.experian.co/", name = "ComputecSTSDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface ComputecSTSDelegate {

    @WebMethod
    @Action(input = "http://sts.computec.experian.co/ComputecSTSDelegate/obtenerTokenRequest", output = "http://sts.computec.experian.co/ComputecSTSDelegate/obtenerTokenResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://sts.computec.experian.co/ComputecSTSDelegate/obtenerToken/Fault/Exception")})
    @RequestWrapper(localName = "obtenerToken", targetNamespace = "http://sts.computec.experian.co/", className = "co.com.santander.accesorecursos.soap.resources.token.ObtenerToken")
    @ResponseWrapper(localName = "obtenerTokenResponse", targetNamespace = "http://sts.computec.experian.co/", className = "co.com.santander.accesorecursos.soap.resources.token.ObtenerTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String obtenerToken(
            @WebParam(name = "arg0", targetNamespace = "")
                    co.com.santander.accesorecursos.soap.resources.token.ComputecSTSDTO arg0
    ) throws Exception_Exception;
}
