
package co.com.santander.accesorecursos.soap.resources.token;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T08:16:50.930+02:00
 * Generated source version: 2.7.2
 */

public class ComputecSTSDelegate_ComputecSTSPort_Server {

    protected ComputecSTSDelegate_ComputecSTSPort_Server() throws Throwable {
        System.out.println("Starting Server");
        Object implementor = new ComputecSTSDelegateImpl();
        String address = "https://felec.computec.com/WSSAMLPruebas/ComputecSTSService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Throwable {
        new ComputecSTSDelegate_ComputecSTSPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5L * 60L * 1000L);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
