package co.com.santander.accesorecursos.soap.resources.token;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T08:16:50.942+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "ComputecSTSService", 
                  wsdlLocation = "https://felec.computec.com/WSSAMLPruebas/ComputecSTSService/ComputecSTSService.wsdl",
                  targetNamespace = "http://sts.computec.experian.co/") 
public class ComputecSTSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sts.computec.experian.co/", "ComputecSTSService");
    public final static QName ComputecSTSPort = new QName("http://sts.computec.experian.co/", "ComputecSTSPort");
    static {
        URL url = null;
        try {
            url = new URL("https://felec.computec.com/WSSAMLPruebas/ComputecSTSService/ComputecSTSService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ComputecSTSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://felec.computec.com/WSSAMLPruebas/ComputecSTSService/ComputecSTSService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ComputecSTSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComputecSTSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComputecSTSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComputecSTSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComputecSTSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComputecSTSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ComputecSTSDelegate
     */
    @WebEndpoint(name = "ComputecSTSPort")
    public ComputecSTSDelegate getComputecSTSPort() {
        return super.getPort(ComputecSTSPort, ComputecSTSDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComputecSTSDelegate
     */
    @WebEndpoint(name = "ComputecSTSPort")
    public ComputecSTSDelegate getComputecSTSPort(WebServiceFeature... features) {
        return super.getPort(ComputecSTSPort, ComputecSTSDelegate.class, features);
    }

}
