
package co.com.santander.accesorecursos.soap.resources.token;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-05-11T08:16:50.839+02:00
 * Generated source version: 2.7.2
 * 
 */
public final class ComputecSTSDelegate_ComputecSTSPort_Client {

    private static final Logger LOG = Logger.getLogger(ComputecSTSDelegate_ComputecSTSPort_Client.class.getName());

    private static final QName SERVICE_NAME = new QName("http://sts.computec.experian.co/", "ComputecSTSService");

    private ComputecSTSDelegate_ComputecSTSPort_Client() {
    }



}
