server:
  servlet:
    context-path: /chatbot-acceso-rescursos-soap
  port: 5004

services:
  getToken: https://felec.computec.com/WSSAML/ComputecSTSService/ComputecSTSService.wsdl
  user: bancosantander
  password: 8@Zc024Z7n!#
  documentos: https://felec.computec.com/WSFelecJAXWS/WsFelecService/WsFelecService.wsdl
  usuarioRemoto: santander.
  producto: VEHICULO
  cliente: SANTANDERCOL

jwt:
  secret: a6e21884876f43819523c31033fa697e