server:
  servlet:
    context-path: /chatbot-acceso-rescursos-soap
  port: 5004

services:
  getToken: https://felec.computec.com/WSSAML/ComputecSTSService/ComputecSTSService.wsdl
  user: john
  password: 12345678
  documentos: https://felec.computec.com/WSFelecJAXWSP/WsFelecService/WsFelecService.wsdl
  usuarioRemoto: 122232
  producto: 123121
  cliente: 1231243

