services:
  getToken: https://felec.computec.com/WSSAML/ComputecSTSService/ComputecSTSService.wsdl
  user: pruebasantander
  password: s@nTAzd38!
  documentos: https://felec.computec.com/WSFelecJAXWSP/WsFelecService/WsFelecService.wsdl
  usuarioRemoto: 122232
  producto: 123121
  cliente: 1231243

jwt:
  secret: a6e21884876f43819523c31033fa697e