server:
  servlet:
    context-path: /chatbot-acceso-rescursos-rest
  port: 5004

services:
  getToken: https://felec.computec.com/WSSAML/ComputecSTSService/ComputecSTSService.wsdl
  user: john
  password: 12345678
  documentos: https://felec.computec.com/WSFelecJAXWSP/WsFelecService/WsFelecService.wsdl