server:
  servlet:
    context-path: /chatbot-acceso-datos
  port: 5001

spring:
  datasource:
    url: jdbc:h2:mem:santander
    driverClassName: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: classpath:/db/db.changelog-dev.xml
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false



#show sql values
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  secret: a6e21884876f43819523c31033fa697e