server:
  servlet:
    context-path: /chatbot-acceso-datos
  port: 5001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.15:5432/chatbot
    username: postgres
    password: 12345678
  flyway:
    schemas: public
    table: chatbot_acceso_datos_flyway_schema_history
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false