spring:
  datasource:
    jndi-name: java:/MSSQLDS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        default_schema: whatsappws
    show-sql: false
    generate-ddl: false

jwt:
  secret: a6e21884876f43819523c31033fa697e