spring:
  datasource:
    jndi-name: java:/MSSQLDS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        default_schema: whatsappws
    show-sql: false
    generate-ddl: false