spring:
  liquibase:
    change-log: classpath:/db/db.changelog-prod.xml
  datasource:
    jndi-name: java:/MSSQLDS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        default_schema: whatsappws
    show-sql: true
    generate-ddl: false

#show sql values
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace