server:
  servlet:
    context-path: /chatbot-acceso-datos
  port: 5001

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;servername=172.60.1.4;databaseName=bdpremierprueba_0306
    username: WhatsApp
    password: W4t54pp2020
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    generate-ddl: false

#show sql values
logging:
  path: C:\chatbot\
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


