server:
  servlet:
    context-path: /chatbot-backend
  port: 5000
  ssl:
    key-store: classpath:santanderbot.p12
    key-store-password: changeme
    keyStoreType: PKCS12


jwt:
  secret: a6e21884876f43819523c31033fa697e