server:
  servlet:
    context-path: /chatbot-backend
  port: 5000

  ssl:
    key-store: classpath:santanderbot.p12
    key-store-password: changeme
    keyStoreType: PKCS12

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

jwt:
  secret: a6e21884876f43819523c31033fa697e

clientes:
  url:
    base: http://www.mocky.io
    creditosUsuario: /v2/5e9038263300003c7227d5a4

security:
  semilla: 1234567890123456


feignclient:
  usuario-app:
    url: http://localhost:5001/chatbot-acceso-datos/v1/usuarioapp/
    service-name: usuario-app

