server:
  servlet:
    context-path: /chatbot-backend
  port: 5000

  ssl:
    key-store: classpath:santanderbot.p12
    key-store-password: changeme
    keyStoreType: PKCS12

logging:
  level:
    co:
      com:
        santander:
          chatbot:
            backend:
              web:
                client: DEBUG



jwt:
  secret: a6e21884876f43819523c31033fa697e


feignclient:
  usuario-app:
    url: http://localhost:5001/chatbot-acceso-datos/v1/usuarioapp/
    service-name: usuario-app

