server:
  servlet:
    context-path: /chatbot-backend
  port: 5000

  ssl:
    key-store: classpath:santanderbot.p12
    key-store-password: changeme
    keyStoreType: PKCS12

logging:
  level:
    co:
      com:
        santander:
          chatbot:
            acceso:
              recursos:
                clients: DEBUG


jwt:
  secret: a6e21884876f43819523c31033fa697e

clientes:
  url:
    base: http://www.mocky.io
    creditosUsuario: /v2/5e9038263300003c7227d5a4
    baseUrlCliente: http://localhost:5001/chatbot-acceso-datos
    baseUrlSoa: http://localhost:5004/chatbot-acceso-rescursos-soap
    consultaDocumentos: /v1/extracto/consultar-documentos
    envioMailDocumentos: /v1/extracto/envio-mail-documento
    consultaCliente: /v1/cliente/
    consultaProcesoExistente: /v1/infowhatsappwscontroller/validateexistingprocess/
    guardarProceso: /v1/infowhatsappwscontroller/
    consultaClienteByTelAndNumCred: /v1/cliente/telAndNumCredit/
    consultaProcesoParametros: /v1/parametros-servicio/consultar-proceso
    consultaParametrosByServicio: /v1/parametros-servicio/servicio/
    consultaCedulaAndCredito: /v1/cliente/cedulaAndNumCredit/
    pseUrl: /v1/pse-param/
    terminosCondiciones: /v1/terminos-condiciones/
    logger: /v1/logger/



security:
  semilla: 1234567890123456


feignclient:
  usuario-app:
    url: http://localhost:5001/chatbot-acceso-datos/v1/usuarioapp/
    service-name: usuario-app

