server:
  servlet:
    context-path: /chatbot-backend-web
  port: 5000
  ssl:
    key-store: classpath:santanderbot.p12
    key-store-password: changeme
    keyStoreType: PKCS12

logging:
  level:
    co:
      com:
        santander:
          chatbot:
            acceso:
              recursos:
                clients: DEBUG


jwt:
  secret: a6e21884876f43819523c31033fa697e

clientes:
  url:
    baseUrlCliente: http://localhost:5001/chatbot-acceso-datos
    baseUrlSoa: http://localhost:5004/chatbot-acceso-rescursos-soap
    #baseUrlCliente: http://172.60.1.3:28080/chatbot-acceso-datos
    #baseUrlSoa: http://172.60.1.3:28080/chatbot-acceso-rescursos-rest

    insercionIdDocumento: /v1/id-documento/
    consultaIdDocumentoById: /v1/id-documento/{id}/
    consultaDocumentos: /v1/extracto/consultar-documentos
    envioMailDocumentos: /v1/extracto/envio-mail-documento
    consultaCliente: /v1/cliente/
    consultaProcesoExistente: /v1/infowhatsappwscontroller/validateexistingprocess/
    guardarProceso: /v1/infowhatsappwscontroller/
    consultaClienteByTelAndNumCred: /v1/cliente/telAndNumCredit/
    consultaProcesoParametros: /v1/parametros-servicio/consultar-proceso
    consultaParametrosByServicio: /v1/parametros-servicio/servicio/
    consultaCedulaAndCredito: /v1/cliente/cedulaAndNumCredit/
    pseUrl: /v1/pse-param/
    terminosCondiciones: /v1/terminos-condiciones/
    logger: /v1/logger/
    saveParametosApp: /v1/parametros-app/
    consultaParametosApp: /v1/parametros-app/

security:
  semilla: 1234567890123456